function total = problem2evenFibonnaciNumbers(limit)
%% Euler Project Problem 2 - Even Fibonnaci Numbers

% Each new term in the Fibonacci sequence is generated by adding the 
% previous two terms. By starting with 1 and 2, the first 10 terms will be:

% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

% By considering the terms in the Fibonacci sequence whose values do not
% exceed four million, find the sum of the even-valued terms.

%% Method

fibNums = [];
fibNums(1)=1; fibNums(2)=1;
i = 2;

while fibNums(i) < limit
    % create list of Fibonnaci numbers up to limit
    i = i + 1;
    fibNums(i) = fibNums(i-1)+fibNums(i-2);
    
end

fibNums = fibNums(1:i-1); % remove final value as while loop exceeds limit

evenFibs = zeros(1,numel(fibNums));
k = 0;

for j = 1:numel(fibNums) % extract even numbers
    if mod(fibNums(j),2)==0
        k = k + 1;
        evenFibs(k) = fibNums(j);
    end
end

evenFibs = evenFibs(1:k); % remove trailing zeros

total = sum(evenFibs); % return total




end